// frontend/src/vue/NcSwap.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import { OpenCEXApi, type QuoteResult } from "../shared/api";
import { CHAINS, toWei } from "../shared/chains";
import {
  connectInjected, connectWalletConnect, switchChain, sendTx, approveToken, disconnectWC, type WalletState,
} from "../shared/walletconnect";

const props = withDefaults(defineProps<{ apiBase?: string; authToken?: string; wcProjectId?: string }>(), {
  apiBase: "/api/v1",
  authToken: "",
  wcProjectId: (import.meta as any).env?.VITE_WC_PROJECT_ID || "",
});

const TOKENS = ["ETH", "USDT", "USDC", "BNB", "MATIC"];
const api = computed(() => new OpenCEXApi(props.apiBase, props.authToken || undefined));
const wallet = ref<WalletState>({ address: null, chainId: 1, provider: null });
const chainId = ref(1);
const sell = ref("ETH");
const buy = ref("USDT");
const amount = ref("0.01");
const quote = ref<QuoteResult | null>(null);
const status = ref("Ready.");
const statusKind = ref<"" | "ok" | "err">("");
const busy = ref(false);

function setMsg(msg: string, kind: "" | "ok" | "err" = "") { status.value = msg; statusKind.value = kind; }
const short = computed(() =>
  wallet.value.address ? `${wallet.value.address.slice(0, 6)}…${wallet.value.address.slice(-4)}` : "Not connected"
);

async function onConnectMM() {
  try {
    const w = await connectInjected();
    wallet.value = w; chainId.value = w.chainId; setMsg("MetaMask connected.", "ok");
    if (w.address) await api.value.registerSession("non_custodial", w.address, w.chainId);
  } catch (e) { setMsg(String((e as Error).message), "err"); }
}

async function onConnectWC() {
  if (!props.wcProjectId) return setMsg("Set VITE_WC_PROJECT_ID for WalletConnect.", "err");
  try {
    busy.value = true;
    const w = await connectWalletConnect(props.wcProjectId, chainId.value);
    wallet.value = w; chainId.value = w.chainId; setMsg("WalletConnect connected.", "ok");
    if (w.address) await api.value.registerSession("non_custodial", w.address, w.chainId);
  } catch (e) { setMsg(String((e as Error).message), "err"); }
  finally { busy.value = false; }
}

function onDisconnect() {
  disconnectWC();
  wallet.value = { address: null, chainId: 1, provider: null };
  quote.value = null; setMsg("Disconnected.");
}

async function onQuote() {
  if (!wallet.value.address) return setMsg("Connect wallet first.", "err");
  try {
    busy.value = true; setMsg("Fetching quote…");
    const q = await api.value.getNcQuote({
      chainId: chainId.value, sell: sell.value, buy: buy.value,
      sellAmount: toWei(amount.value, sell.value), taker: wallet.value.address,
    });
    quote.value = q;
    setMsg(q.needs_allowance ? "Quote ready — approval required." : "Quote ready.", "ok");
  } catch (e) { quote.value = null; setMsg("Quote failed: " + (e as Error).message, "err"); }
  finally { busy.value = false; }
}

async function onSwap() {
  if (!wallet.value.address || !wallet.value.provider || !quote.value?.transaction) return;
  try {
    busy.value = true;
    await switchChain(wallet.value.provider, chainId.value);
    const q = quote.value;
    if (q.needs_allowance && q.allowance_spender && q.sell_token) {
      setMsg("Approve token in wallet…");
      await approveToken(wallet.value.provider, wallet.value.address, q.sell_token, q.allowance_spender);
    }
    setMsg("Confirm swap in wallet…");
    const hash = await sendTx(wallet.value.provider, wallet.value.address, q.transaction!);
    setMsg("Submitted: " + hash, "ok");
  } catch (e) { setMsg("Swap failed: " + (e as Error).message, "err"); }
  finally { busy.value = false; }
}
</script>

<template>
  <div class="card">
    <h1>Non-Custodial Swap</h1>
    <p class="sub">Funds stay in your wallet · 0x + OpenCEX · WC v2</p>
    <div class="wallet">{{ short }}</div>
    <label>Network</label>
    <select v-model.number="chainId">
      <option v-for="(c, id) in CHAINS" :key="id" :value="Number(id)">{{ c.name }}</option>
    </select>
    <div class="pair">
      <div><label>Sell</label><select v-model="sell"><option v-for="t in TOKENS" :key="t">{{ t }}</option></select></div>
      <div class="arrow">→</div>
      <div><label>Buy</label><select v-model="buy"><option v-for="t in TOKENS" :key="t">{{ t }}</option></select></div>
    </div>
    <label>Amount</label>
    <input v-model="amount" type="text" />
    <div v-if="quote" class="price">You receive ≈ {{ quote.buy_amount || "?" }} (raw)</div>
    <template v-if="!wallet.address">
      <button class="btn-sec" :disabled="busy" @click="onConnectMM">MetaMask</button>
      <button class="btn-prim" :disabled="busy" @click="onConnectWC">WalletConnect</button>
    </template>
    <template v-else>
      <button class="btn-sec" @click="onDisconnect">Disconnect</button>
      <button class="btn-prim" :disabled="busy" @click="onQuote">Get Quote</button>
      <button class="btn-prim" :disabled="busy || !quote" @click="onSwap">Swap</button>
    </template>
    <div class="status" :class="statusKind">{{ status }}</div>
  </div>
</template>

<style scoped>
.card { width: 100%; max-width: 420px; background: #12161c; border: 1px solid #1e2329; border-radius: 16px; padding: 24px; color: #eaecef; font-family: system-ui, sans-serif; }
h1 { font-size: 1.25rem; margin: 0 0 4px; }
.sub { color: #848e9c; font-size: 0.85rem; margin-bottom: 20px; }
.wallet { font-size: 0.75rem; color: #0ecb81; margin-bottom: 12px; }
label { display: block; font-size: 0.75rem; color: #848e9c; margin: 12px 0 6px; }
select, input { width: 100%; padding: 12px 14px; border-radius: 8px; border: 1px solid #1e2329; background: #0b0e11; color: #eaecef; font-size: 1rem; }
.pair { display: grid; grid-template-columns: 1fr auto 1fr; gap: 8px; align-items: end; }
.arrow { color: #848e9c; padding-bottom: 12px; text-align: center; }
button { width: 100%; padding: 14px; margin-top: 8px; border: none; border-radius: 10px; font-size: 1rem; font-weight: 600; cursor: pointer; }
.btn-prim { background: #f0b90b; color: #000; }
.btn-prim:disabled { opacity: 0.5; cursor: not-allowed; }
.btn-sec { background: #1e2329; color: #eaecef; }
.price { font-size: 0.9rem; color: #848e9c; margin-top: 8px; }
.status { margin-top: 16px; padding: 12px; border-radius: 8px; background: #0b0e11; font-size: 0.8rem; color: #848e9c; word-break: break-all; }
.status.ok { color: #0ecb81; border: 1px solid #0ecb81; }
.status.err { color: #f6465d; border: 1px solid #f6465d; }
</style>

// frontend/src/react/NcSwap.tsx
import React, { useCallback, useMemo, useState } from "react";
import { OpenCEXApi, type QuoteResult } from "../shared/api";
import { CHAINS, toWei } from "../shared/chains";
import {
  connectInjected, connectWalletConnect, switchChain, sendTx, approveToken, disconnectWC, type WalletState,
} from "../shared/walletconnect";

const TOKENS = ["ETH", "USDT", "USDC", "BNB", "MATIC"] as const;

export type NcSwapProps = {
  apiBase?: string;
  authToken?: string;
  wcProjectId?: string;
};

export function NcSwap({
  apiBase = "/api/v1",
  authToken,
  wcProjectId = (import.meta as any).env?.VITE_WC_PROJECT_ID || "",
}: NcSwapProps) {
  const api = useMemo(() => new OpenCEXApi(apiBase, authToken), [apiBase, authToken]);
  const [wallet, setWallet] = useState<WalletState>({ address: null, chainId: 1, provider: null });
  const [chainId, setChainId] = useState(1);
  const [sell, setSell] = useState("ETH");
  const [buy, setBuy] = useState("USDT");
  const [amount, setAmount] = useState("0.01");
  const [quote, setQuote] = useState<QuoteResult | null>(null);
  const [status, setStatus] = useState("Ready.");
  const [statusKind, setStatusKind] = useState<"" | "ok" | "err">("");
  const [busy, setBusy] = useState(false);

  const setMsg = (msg: string, kind: "" | "ok" | "err" = "") => { setStatus(msg); setStatusKind(kind); };

  const onConnectMM = useCallback(async () => {
    try {
      const w = await connectInjected();
      setWallet(w); setChainId(w.chainId); setMsg("MetaMask connected.", "ok");
      if (w.address) await api.registerSession("non_custodial", w.address, w.chainId);
    } catch (e) { setMsg(String((e as Error).message), "err"); }
  }, [api]);

  const onConnectWC = useCallback(async () => {
    if (!wcProjectId) return setMsg("Set VITE_WC_PROJECT_ID for WalletConnect.", "err");
    try {
      setBusy(true);
      const w = await connectWalletConnect(wcProjectId, chainId);
      setWallet(w); setChainId(w.chainId); setMsg("WalletConnect connected.", "ok");
      if (w.address) await api.registerSession("non_custodial", w.address, w.chainId);
    } catch (e) { setMsg(String((e as Error).message), "err"); }
    finally { setBusy(false); }
  }, [api, chainId, wcProjectId]);

  const onDisconnect = () => {
    disconnectWC();
    setWallet({ address: null, chainId: 1, provider: null });
    setQuote(null); setMsg("Disconnected.");
  };

  const onQuote = async () => {
    if (!wallet.address) return setMsg("Connect wallet first.", "err");
    try {
      setBusy(true); setMsg("Fetching quote…");
      const q = await api.getNcQuote({ chainId, sell, buy, sellAmount: toWei(amount, sell), taker: wallet.address });
      setQuote(q);
      setMsg(q.needs_allowance ? "Quote ready — approval required." : "Quote ready.", "ok");
    } catch (e) { setQuote(null); setMsg("Quote failed: " + (e as Error).message, "err"); }
    finally { setBusy(false); }
  };

  const onSwap = async () => {
    if (!wallet.address || !wallet.provider || !quote?.transaction) return;
    try {
      setBusy(true);
      await switchChain(wallet.provider, chainId);
      if (quote.needs_allowance && quote.allowance_spender && quote.sell_token) {
        setMsg("Approve token in wallet…");
        await approveToken(wallet.provider, wallet.address, quote.sell_token, quote.allowance_spender);
      }
      setMsg("Confirm swap in wallet…");
      const hash = await sendTx(wallet.provider, wallet.address, quote.transaction);
      setMsg("Submitted: " + hash, "ok");
    } catch (e) { setMsg("Swap failed: " + (e as Error).message, "err"); }
    finally { setBusy(false); }
  };

  const short = wallet.address ? `${wallet.address.slice(0, 6)}…${wallet.address.slice(-4)}` : "Not connected";

  return (
    <div style={s.card}>
      <h1 style={s.h1}>Non-Custodial Swap</h1>
      <p style={s.sub}>Funds stay in your wallet · 0x + OpenCEX · WC v2</p>
      <div style={s.wallet}>{short}</div>
      <label style={s.label}>Network</label>
      <select style={s.input} value={chainId} onChange={(e) => setChainId(Number(e.target.value))}>
        {Object.entries(CHAINS).map(([id, c]) => <option key={id} value={id}>{c.name}</option>)}
      </select>
      <div style={s.pair}>
        <div><label style={s.label}>Sell</label>
          <select style={s.input} value={sell} onChange={(e) => setSell(e.target.value)}>{TOKENS.map((t) => <option key={t}>{t}</option>)}</select></div>
        <div style={{ paddingBottom: 12, color: "#848e9c" }}>→</div>
        <div><label style={s.label}>Buy</label>
          <select style={s.input} value={buy} onChange={(e) => setBuy(e.target.value)}>{TOKENS.map((t) => <option key={t}>{t}</option>)}</select></div>
      </div>
      <label style={s.label}>Amount</label>
      <input style={s.input} value={amount} onChange={(e) => setAmount(e.target.value)} />
      {quote && <div style={s.price}>You receive ≈ {quote.buy_amount || "?"} (raw)</div>}
      {!wallet.address ? (
        <>
          <button style={s.btnSec} onClick={onConnectMM} disabled={busy}>MetaMask</button>
          <button style={s.btnPrim} onClick={onConnectWC} disabled={busy}>WalletConnect</button>
        </>
      ) : (
        <>
          <button style={s.btnSec} onClick={onDisconnect}>Disconnect</button>
          <button style={s.btnPrim} onClick={onQuote} disabled={busy}>Get Quote</button>
          <button style={s.btnPrim} onClick={onSwap} disabled={busy || !quote}>Swap</button>
        </>
      )}
      <div style={{ ...s.status, ...(statusKind === "ok" ? s.ok : {}), ...(statusKind === "err" ? s.err : {}) }}>{status}</div>
    </div>
  );
}

const s: Record<string, React.CSSProperties> = {
  card: { width: "100%", maxWidth: 420, background: "#12161c", border: "1px solid #1e2329", borderRadius: 16, padding: 24, color: "#eaecef", fontFamily: "system-ui, sans-serif" },
  h1: { fontSize: "1.25rem", margin: "0 0 4px" },
  sub: { color: "#848e9c", fontSize: "0.85rem", marginBottom: 20 },
  wallet: { fontSize: "0.75rem", color: "#0ecb81", marginBottom: 12 },
  label: { display: "block", fontSize: "0.75rem", color: "#848e9c", margin: "12px 0 6px" },
  input: { width: "100%", padding: "12px 14px", borderRadius: 8, border: "1px solid #1e2329", background: "#0b0e11", color: "#eaecef", fontSize: "1rem" },
  pair: { display: "grid", gridTemplateColumns: "1fr auto 1fr", gap: 8, alignItems: "end" },
  btnPrim: { width: "100%", padding: 14, marginTop: 8, border: "none", borderRadius: 10, background: "#f0b90b", color: "#000", fontWeight: 600, cursor: "pointer" },
  btnSec: { width: "100%", padding: 14, marginTop: 8, border: "none", borderRadius: 10, background: "#1e2329", color: "#eaecef", fontWeight: 600, cursor: "pointer" },
  price: { fontSize: "0.9rem", color: "#848e9c", marginTop: 8 },
  status: { marginTop: 16, padding: 12, borderRadius: 8, background: "#0b0e11", fontSize: "0.8rem", color: "#848e9c", wordBreak: "break-all" },
  ok: { color: "#0ecb81", border: "1px solid #0ecb81" },
  err: { color: "#f6465d", border: "1px solid #f6465d" },
};

export default NcSwap;
